#!/usr/bin/env python3
"""M8.2 xform: rewrite a staged cREXX unit so GCC380 can compile it.

    xform.py STAGE UNIT OUTDIR    -> OUTDIR/UNIT.c (preprocessed, rewritten)

GCC380's i370 back end has no 64-bit add: every long long '+' (and every
'-' of a constant, which GCC folds into an add) ends in an internal
compiler error.  Its 64-bit subtract, shifts, compares and the libcalls
work.  So the unit is preprocessed on the PC, parsed (pycparser), typed,
and every 64-bit +, -, +=, -=, ++ and -- becomes a call to CRXLGCC C's
crxadd64 / crxsub64 / crxadt64 / crxinc64, which work in 32-bit halves.

The output is one self-contained C file: the unit with only the
declarations it uses (the headers are pruned to what is reachable from
the unit's own definitions)."""
import os
import re
import subprocess
import sys

from pycparser import c_ast, c_generator, c_parser

HERE = os.path.dirname(os.path.abspath(__file__))


_orig_designator = c_parser.CParser._parse_designator


def _parse_designator(self):
    # pycparser keeps [ID] and .ID alike and prints both as .ID:
    # wrap an index so the generator prints [ID]
    if self._peek_type() == "LBRACKET":
        return c_ast.ExprList([_orig_designator(self)])
    return _orig_designator(self)


c_parser.CParser._parse_designator = _parse_designator

PROLOGUE = '''/* M8.2: generated by xform.py from the staged unit -- do not edit */
#define __crx_crab() ({GCCCRAB *__t; __asm__("L %0,72(13)" : "=d" (__t)); __t;})
long long crxadd64(long long a, long long b);
long long crxsub64(long long a, long long b);
long long crxadt64(long long *p, long long b);
long long crxinc64(long long *p, long long d, int post);
int crxcmp64(long long a, long long b);
int crxucm64(unsigned long long a, unsigned long long b);
long crxsw64(long long a);
'''
HELPERS = ('crxadd64', 'crxsub64', 'crxadt64', 'crxinc64')
IHELPERS = ('crxcmp64', 'crxucm64', 'crxsw64')

INT = {'char': 8, 'short': 16, 'int': 32, 'long': 32, '_Bool': 8}


class Types:
    def __init__(self, ast):
        self.typedefs = {}
        self.tags = {}
        self.globals = {}
        self.enumconst = set()
        LL = c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['long', 'long']))
        INTT = c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['int']))
        for h in HELPERS:
            self.globals[h] = c_ast.FuncDecl(None, LL)
        for h in IHELPERS:
            self.globals[h] = c_ast.FuncDecl(None, INTT)
        for ext in ast.ext:
            self.note(ext)

    def note(self, n):
        """record typedefs, tags and global names from a declaration"""
        if isinstance(n, c_ast.Typedef):
            self.typedefs[n.name] = n.type
            self.tags_in(n.type)
        elif isinstance(n, c_ast.Decl):
            if n.name:
                self.globals[n.name] = n.type
            self.tags_in(n.type)
        elif isinstance(n, c_ast.FuncDef):
            self.globals[n.decl.name] = n.decl.type

    def tags_in(self, t):
        while isinstance(t, (c_ast.PtrDecl, c_ast.ArrayDecl, c_ast.TypeDecl, c_ast.FuncDecl)):
            t = t.type
        if isinstance(t, (c_ast.Struct, c_ast.Union)) and t.decls is not None and t.name:
            self.tags[(type(t).__name__, t.name)] = t
        if isinstance(t, (c_ast.Struct, c_ast.Union)) and t.decls:
            for d in t.decls:
                self.tags_in(d.type)
        if isinstance(t, c_ast.Enum) and t.values:
            for e in t.values.enumerators:
                self.enumconst.add(e.name)

    # ---- simplified types: ('int', bits, unsigned) ('float',) ('ptr', T)
    #      ('struct', node) ('func', T) ('void',) or None (unknown)
    def resolve(self, t, depth=0):
        if t is None or depth > 40:
            return None
        if isinstance(t, c_ast.Typename) or isinstance(t, c_ast.Decl):
            return self.resolve(t.type, depth + 1)
        if isinstance(t, c_ast.TypeDecl):
            return self.resolve(t.type, depth + 1)
        if isinstance(t, c_ast.PtrDecl):
            return ('ptr', t.type)
        if isinstance(t, c_ast.ArrayDecl):
            return ('ptr', t.type)
        if isinstance(t, c_ast.FuncDecl):
            return ('func', t.type)
        if isinstance(t, (c_ast.Struct, c_ast.Union)):
            if t.decls is None:
                t = self.tags.get((type(t).__name__, t.name), t)
            return ('struct', t)
        if isinstance(t, c_ast.Enum):
            return ('int', 32, False)
        if isinstance(t, c_ast.IdentifierType):
            names = [x for x in t.names if x not in ('signed', 'const', 'volatile')]
            uns = 'unsigned' in t.names
            names = [x for x in names if x != 'unsigned']
            if not names:
                return ('int', 32, uns)
            if 'double' in names or 'float' in names:
                return ('float',)
            if names == ['void']:
                return ('void',)
            if names.count('long') == 2:
                return ('int', 64, uns)
            if len(names) == 1 and names[0] in self.typedefs:
                return self.resolve(self.typedefs[names[0]], depth + 1)
            for k in ('char', 'short', '_Bool'):
                if k in names:
                    return ('int', INT[k], uns)
            if 'long' in names or 'int' in names:
                return ('int', 32, uns)
            if len(names) == 1 and names[0] == '__builtin_va_list':
                return ('ptr', None)
            return None
        return None

    def field(self, st, name):
        if not st or st[0] != 'struct':
            return None
        node = st[1]
        if not isinstance(node, (c_ast.Struct, c_ast.Union)) or node.decls is None:
            return None
        for d in node.decls:
            if d.name == name:
                return self.resolve(d.type)
            if d.name is None:                       # anonymous member
                r = self.field(self.resolve(d.type), name)
                if r:
                    return r
        return None


def arith(a, b):
    """usual arithmetic conversions"""
    if not a or not b:
        return None
    if a[0] == 'float' or b[0] == 'float':
        return ('float',) if a[0] in ('float', 'int') and b[0] in ('float', 'int') else None
    if a[0] == 'int' and b[0] == 'int':
        if a[1] == 64 or b[1] == 64:
            uns = (a[1] == 64 and a[2]) or (b[1] == 64 and b[2])
            return ('int', 64, uns)
        return ('int', 32, a[2] and a[1] == 32 or b[2] and b[1] == 32)
    return None


def is64(t):
    return t is not None and t[0] == 'int' and t[1] == 64


def const_type(c):
    if c.type in ('char',):
        return ('int', 32, False)
    if c.type in ('float', 'double'):
        return ('float',)
    v = c.value.lower()
    if 'll' in v:
        return ('int', 64, 'u' in v)
    try:
        n = int(v.rstrip('ul'), 0) if not re.match(r'0[0-7]+$', v.rstrip('ul')) else int(v.rstrip('ul'), 8)
    except ValueError:
        return ('int', 32, False)
    if n > 0xFFFFFFFF or (n > 0x7FFFFFFF and v.rstrip('ul').isdigit() and 'u' not in v):
        return ('int', 64, 'u' in v)
    return ('int', 32, 'u' in v or n > 0x7FFFFFFF)


LLT = c_ast.Typename(None, [], None, c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['long', 'long'])))
ULLT = c_ast.Typename(None, [], None, c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['unsigned', 'long', 'long'])))
LLP = c_ast.Typename(None, [], None, c_ast.PtrDecl([], c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['long', 'long']))))


def call(name, *args):
    return c_ast.FuncCall(c_ast.ID(name), c_ast.ExprList(list(args)))


def cast(t, e):
    return c_ast.Cast(t, e)


class Xform:
    def __init__(self, ty):
        self.ty = ty
        self.count = 0
        self.unknown = 0

    # ---- scopes
    def lookup(self, scopes, name):
        for s in reversed(scopes):
            if name in s:
                return self.ty.resolve(s[name])
        if name in self.ty.globals:
            return self.ty.resolve(self.ty.globals[name])
        if name in self.ty.enumconst:
            return ('int', 32, False)
        return None

    def typeof(self, e, sc):
        T = self.ty
        if isinstance(e, c_ast.Constant):
            if e.type == 'string':
                return ('ptr', None)
            return const_type(e)
        if isinstance(e, c_ast.ID):
            return self.lookup(sc, e.name)
        if isinstance(e, c_ast.Cast):
            return T.resolve(e.to_type)
        if isinstance(e, c_ast.UnaryOp):
            if e.op == '&':
                return ('ptr', None)
            if e.op == '*':
                p = self.typeof(e.expr, sc)
                return T.resolve(p[1]) if p and p[0] == 'ptr' and p[1] is not None else None
            if e.op in ('sizeof', '_Alignof'):
                return ('int', 32, True)
            if e.op == '!':
                return ('int', 32, False)
            t = self.typeof(e.expr, sc)
            if e.op in ('-', '+', '~') and t and t[0] == 'int' and t[1] < 32:
                return ('int', 32, False)
            return t
        if isinstance(e, c_ast.BinaryOp):
            if e.op in ('<', '>', '<=', '>=', '==', '!=', '&&', '||'):
                return ('int', 32, False)
            a, b = self.typeof(e.left, sc), self.typeof(e.right, sc)
            if e.op in ('<<', '>>'):
                return a if a and a[0] == 'int' and a[1] >= 32 else ('int', 32, False) if a else None
            if e.op in ('+', '-') and a and a[0] == 'ptr':
                return ('int', 32, False) if e.op == '-' and b and b[0] == 'ptr' else a
            if e.op == '+' and b and b[0] == 'ptr':
                return b
            return arith(a, b)
        if isinstance(e, c_ast.Assignment):
            return self.typeof(e.lvalue, sc)
        if isinstance(e, c_ast.TernaryOp):
            a, b = self.typeof(e.iftrue, sc), self.typeof(e.iffalse, sc)
            if a and a[0] == 'int' and b and b[0] == 'int':
                return arith(a, b)
            return a or b
        if isinstance(e, c_ast.FuncCall):
            f = self.typeof(e.name, sc)
            if f and f[0] == 'ptr' and f[1] is not None:
                f = T.resolve(f[1])
            if f and f[0] == 'func':
                return T.resolve(f[1])
            return None
        if isinstance(e, c_ast.StructRef):
            s = self.typeof(e.name, sc)
            if e.type == '->':
                s = T.resolve(s[1]) if s and s[0] == 'ptr' and s[1] is not None else None
            return T.field(s, e.field.name)
        if isinstance(e, c_ast.ArrayRef):
            p = self.typeof(e.name, sc)
            if p and p[0] == 'ptr' and p[1] is not None:
                return T.resolve(p[1])
            q = self.typeof(e.subscript, sc)        # i[a]
            if q and q[0] == 'ptr' and q[1] is not None:
                return T.resolve(q[1])
            return None
        if isinstance(e, c_ast.ExprList):
            return self.typeof(e.exprs[-1], sc) if e.exprs else None
        if isinstance(e, c_ast.CompoundLiteral):
            return T.resolve(e.type)
        return None

    # ---- rewriting
    def x(self, n, sc):
        """rewrite node n (in place where possible); returns the node"""
        if n is None:
            return None
        if isinstance(n, c_ast.FuncDef):
            s = {}
            ft = n.decl.type
            if isinstance(ft, c_ast.FuncDecl) and ft.args:
                for p in ft.args.params:
                    if isinstance(p, c_ast.Decl) and p.name:
                        s[p.name] = p.type
            n.body = self.x(n.body, sc + [s])
            return n
        if isinstance(n, c_ast.Compound):
            s = {}
            sc2 = sc + [s]
            items = n.block_items or []
            for i, it in enumerate(items):
                if isinstance(it, c_ast.Decl):
                    if it.name:
                        s[it.name] = it.type
                    self.ty.tags_in(it.type)
                    if it.init is not None:
                        it.init = self.x(it.init, sc2)
                elif isinstance(it, c_ast.Typedef):
                    self.ty.typedefs[it.name] = it.type
                    self.ty.tags_in(it.type)
                else:
                    items[i] = self.x(it, sc2)
            return n
        if isinstance(n, c_ast.For):
            s = {}
            sc2 = sc + [s]
            if isinstance(n.init, c_ast.DeclList):
                for d in n.init.decls:
                    s[d.name] = d.type
                    if d.init is not None:
                        d.init = self.x(d.init, sc2)
            else:
                n.init = self.x(n.init, sc2)
            n.cond = self.boolify(self.x(n.cond, sc2), sc2)
            n.next = self.x(n.next, sc2)
            n.stmt = self.x(n.stmt, sc2)
            return n
        if isinstance(n, c_ast.Decl):
            if n.init is not None:
                n.init = self.x(n.init, sc)
            return n
        # generic: rewrite children first
        for name in n.__slots__:
            if name in ('coord', '__weakref__'):
                continue
            v = getattr(n, name, None)
            if isinstance(v, c_ast.Node):
                if isinstance(n, (c_ast.Cast, c_ast.Typename)) and name in ('to_type', 'type'):
                    continue
                if isinstance(n, c_ast.UnaryOp) and n.op in ('sizeof', '_Alignof'):
                    continue
                if isinstance(n, c_ast.StructRef) and name == 'field':
                    continue
                setattr(n, name, self.x(v, sc))
            elif isinstance(v, list):
                for i, it in enumerate(v):
                    if isinstance(it, c_ast.Node):
                        v[i] = self.x(it, sc)
        return self.rewrite(n, sc)

    def cmp64(self, e, sc):
        """a 64-bit comparison under && or ||: GCC folds those pairs into
        range tests, which subtract a constant -- an add.  Compare by call."""
        if isinstance(e, c_ast.BinaryOp) and e.op in ('<', '>', '<=', '>=', '==', '!='):
            a, b = self.typeof(e.left, sc), self.typeof(e.right, sc)
            t = arith(a, b)
            if is64(t):
                self.count += 1
                f = 'crxucm64' if t[2] else 'crxcmp64'
                ct = ULLT if t[2] else LLT
                return c_ast.BinaryOp(e.op, call(f, cast(ct, e.left), cast(ct, e.right)),
                                      c_ast.Constant('int', '0'))
        return e

    def boolify(self, e, sc):
        """a 64-bit value used as a condition: compare by call"""
        if e is None:
            return e
        e = self.cmp64(e, sc)
        t = self.typeof(e, sc)
        if is64(t):
            self.count += 1
            return c_ast.BinaryOp('!=', call('crxucm64' if t[2] else 'crxcmp64',
                                             cast(ULLT if t[2] else LLT, e),
                                             cast(ULLT if t[2] else LLT, c_ast.Constant('int', '0'))),
                                  c_ast.Constant('int', '0'))
        return e

    def rewrite(self, n, sc):
        # every 64-bit comparison and 64-bit truth test by call: GCC380
        # folds pairs into range tests (an add it cannot do) and runs out
        # of register pairs reloading its DImode compare-and-branch
        if isinstance(n, c_ast.BinaryOp) and n.op in ('&&', '||'):
            n.left = self.boolify(n.left, sc)
            n.right = self.boolify(n.right, sc)
            return n
        if isinstance(n, c_ast.BinaryOp) and n.op in ('<', '>', '<=', '>=', '==', '!='):
            return self.cmp64(n, sc)
        if isinstance(n, c_ast.UnaryOp) and n.op == '!':
            n.expr = self.boolify(n.expr, sc)
            return n
        if isinstance(n, (c_ast.If, c_ast.While, c_ast.DoWhile, c_ast.TernaryOp)):
            n.cond = self.boolify(n.cond, sc)
            return n
        if isinstance(n, c_ast.Switch):
            t = self.typeof(n.cond, sc)
            if is64(t):
                self.count += 1
                n.cond = call('crxsw64', cast(LLT, n.cond))
            return n
        if isinstance(n, c_ast.BinaryOp) and n.op in ('+', '-'):
            t = self.typeof(n, sc)
            if t is None:
                self.unknown += 1
                if os.environ.get('XFDEBUG'):
                    print('unknown type:', n.coord, c_generator.CGenerator().visit(n)[:100])
            if is64(t):
                self.count += 1
                r = call('crxadd64' if n.op == '+' else 'crxsub64', cast(LLT, n.left), cast(LLT, n.right))
                return cast(ULLT, r) if t[2] else r
        if isinstance(n, c_ast.Assignment) and n.op in ('+=', '-='):
            lt = self.typeof(n.lvalue, sc)
            rt = self.typeof(n.rvalue, sc)
            if is64(lt) and (rt is None or rt[0] == 'int'):
                self.count += 1
                rv = cast(LLT, n.rvalue)
                if n.op == '-=':
                    rv = c_ast.UnaryOp('-', rv)
                r = call('crxadt64', cast(LLP, c_ast.UnaryOp('&', n.lvalue)), rv)
                return cast(ULLT, r) if lt[2] else r
            if lt and lt[0] == 'int' and is64(rt):
                self.count += 1        # int += long long: computed in 64 bits
                op = 'crxadd64' if n.op == '+=' else 'crxsub64'
                return c_ast.Assignment('=', n.lvalue, call(op, cast(LLT, n.lvalue), cast(LLT, n.rvalue)))
        if isinstance(n, c_ast.UnaryOp) and n.op in ('++', '--', 'p++', 'p--'):
            t = self.typeof(n.expr, sc)
            if is64(t):
                self.count += 1
                d = c_ast.Constant('int', '1' if '+' in n.op else '-1')
                r = call('crxinc64', cast(LLP, c_ast.UnaryOp('&', n.expr)), cast(LLT, d),
                         c_ast.Constant('int', '1' if n.op.startswith('p') else '0'))
                return cast(ULLT, r) if t[2] else r
        return n


class Names(c_ast.NodeVisitor):
    """identifiers, type names and tags a node uses"""
    def __init__(self):
        self.ids = set()
        self.tags = set()

    def visit_ID(self, n):
        self.ids.add(n.name)

    def visit_IdentifierType(self, n):
        for x in n.names:
            self.ids.add(x)

    def visit_Struct(self, n):
        if n.name:
            self.tags.add(('Struct', n.name))
        self.generic_visit(n)

    def visit_Union(self, n):
        if n.name:
            self.tags.add(('Union', n.name))
        self.generic_visit(n)

    def visit_Enum(self, n):
        if n.name:
            self.tags.add(('Enum', n.name))
        self.generic_visit(n)

    def visit_StructRef(self, n):
        self.visit(n.name)               # not the field name

    def visit_NamedInitializer(self, n):
        self.visit(n.expr)


def defines(n):
    """names, tags and enum constants a top-level item defines"""
    names, tags = set(), set()
    if isinstance(n, c_ast.FuncDef):
        names.add(n.decl.name)
        return names, tags
    if isinstance(n, (c_ast.Typedef, c_ast.Decl)) and n.name:
        names.add(n.name)
    t = n.type if hasattr(n, 'type') else None
    while isinstance(t, (c_ast.PtrDecl, c_ast.ArrayDecl, c_ast.TypeDecl, c_ast.FuncDecl)):
        t = t.type
    if isinstance(t, (c_ast.Struct, c_ast.Union, c_ast.Enum)):
        if t.name:
            tags.add((type(t).__name__, t.name))
        if isinstance(t, c_ast.Enum) and t.values:
            for e in t.values.enumerators:
                names.add(e.name)
    return names, tags


def prune(ast, unitfile, roots=None):
    """keep the unit's own items (or the items in roots) and what they reach"""
    items = ast.ext
    info = []
    for n in items:
        nm = Names()
        nm.visit(n)
        d, dt = defines(n)
        own = n.coord is not None and os.path.basename(str(n.coord.file)) == unitfile
        info.append((n, own, d, dt, nm.ids, nm.tags))
    keep = [False] * len(items)
    need_ids, need_tags = {'GCCCRAB'}, set()
    by_name, by_tag = {}, {}
    for i, (n, own, d, dt, ids, tags) in enumerate(info):
        for x in d:
            by_name.setdefault(x, []).append(i)
        for x in dt:
            by_tag.setdefault(x, []).append(i)
    if roots is None:
        work = [i for i, inf in enumerate(info) if inf[1]]
    else:
        work = [i for i, n in enumerate(items) if id(n) in roots]
    for x in need_ids:
        work += by_name.get(x, [])
    while work:
        i = work.pop()
        if keep[i]:
            continue
        keep[i] = True
        n, own, d, dt, ids, tags = info[i]
        for x in ids:
            work += [j for j in by_name.get(x, []) if not keep[j]]
        for x in tags:
            work += [j for j in by_tag.get(x, []) if not keep[j]]
    out = []
    for i, n in enumerate(items):
        if keep[i] and not (isinstance(n, c_ast.Decl) and n.name == '__crx_crab'):
            out.append(n)
    ast.ext = out
    return sum(keep)


CPP = ['s390x-linux-gnu-gcc', '-E', '-m31', '-undef', '-nostdinc', '-D__CMS__', '-D__GNUC__=3',
       '-D__GNUC_MINOR__=2', '-D__i370__', '-D__CHAR_UNSIGNED__', '-D__attribute__(x)=',
       '-D__inline__=inline', '-D__inline=inline', '-D__restrict__=', '-D__restrict=',
       '-D__extension__=', '-D__asm__(x)=']


def const_value(e):
    neg = False
    if isinstance(e, c_ast.UnaryOp) and e.op == '-':
        e, neg = e.expr, True
    if isinstance(e, c_ast.Cast):
        e = e.expr
    if not isinstance(e, c_ast.Constant) or e.type not in ('int', 'unsigned int', 'long int',
                                                           'unsigned long int', 'char'):
        return None
    v = e.value.rstrip('uUlL')
    try:
        n = int(v, 16) if v.lower().startswith('0x') else int(v, 8) if (len(v) > 1 and v[0] == '0') \
            else ord(eval(v)) if v.startswith("'") else int(v)
    except Exception:
        return None
    return -n if neg else n


def replace_ids(n, names):
    """replace ID nodes named in names by the node names[name] builds"""
    for slot in n.__slots__:
        if slot in ('coord', '__weakref__'):
            continue
        v = getattr(n, slot, None)
        if isinstance(v, c_ast.ID) and v.name in names and not (isinstance(n, c_ast.StructRef) and slot == 'field'):
            setattr(n, slot, names[v.name]())
        elif isinstance(v, c_ast.Node):
            replace_ids(v, names)
        elif isinstance(v, list):
            for i, it in enumerate(v):
                if isinstance(it, c_ast.ID) and it.name in names:
                    v[i] = names[it.name]()
                elif isinstance(it, c_ast.Node):
                    replace_ids(it, names)


def pack_tables(ast, ty, limit=2000):
    """GCC380 writes one DC per array element and a CMS file holds 65,533
    records: big constant integer tables (lemon's yy_action, yy_lookahead)
    become a union of the bytes, initialised by a string, and the array"""
    names = {}
    for i, n in enumerate(ast.ext):
        if not (isinstance(n, c_ast.Decl) and isinstance(n.type, c_ast.ArrayDecl)
                and isinstance(n.init, c_ast.InitList) and len(n.init.exprs) > limit):
            continue
        et = ty.resolve(n.type.type)
        if not et or et[0] != 'int' or et[1] not in (8, 16, 32):
            continue
        vals = [const_value(e) for e in n.init.exprs]
        if any(v is None for v in vals):
            continue
        size = et[1] // 8
        dim = const_value(n.type.dim) if n.type.dim is not None else len(vals)
        if dim is None or dim < len(vals):
            continue
        vals += [0] * (dim - len(vals))
        data = b''.join((v & ((1 << et[1]) - 1)).to_bytes(size, 'big') for v in vals)
        lit = ''.join('\\x%02x' % b for b in data)
        uname = 'U' + n.name
        elt = n.type.type
        un = c_ast.Union(None, [
            c_ast.Decl('b', [], [], [], [], c_ast.ArrayDecl(
                c_ast.TypeDecl('b', [], None, c_ast.IdentifierType(['unsigned', 'char'])),
                c_ast.Constant('int', str(len(data))), []), None, None),
            c_ast.Decl('a', [], [], [], [], c_ast.ArrayDecl(
                c_ast.TypeDecl('a', [], None, elt.type), c_ast.Constant('int', str(dim)), []), None, None)])
        d = c_ast.Decl(uname, n.quals, n.align, n.storage, n.funcspec,
                       c_ast.TypeDecl(uname, n.type.type.quals, None, un),
                       c_ast.InitList([c_ast.Constant('string', '"' + lit + '"')]), None)
        d.coord = n.coord
        ast.ext[i] = d
        names[n.name] = (lambda u=uname: c_ast.StructRef(c_ast.ID(u), '.', c_ast.ID('a')))
    if names:
        for n in ast.ext:
            if isinstance(n, c_ast.FuncDef):
                replace_ids(n, names)
    return len(names)


def declname_set(t, new):
    while not isinstance(t, c_ast.TypeDecl):
        if not hasattr(t, 'type'):
            return
        t = t.type
    t.declname = new


class Renamer:
    """rename file-scope names, respecting local shadowing"""
    def __init__(self, names):
        self.names = names

    def run(self, n, shadow=frozenset()):
        if n is None:
            return
        if isinstance(n, c_ast.ID):
            if n.name in self.names and n.name not in shadow:
                n.name = self.names[n.name]
            return
        if isinstance(n, c_ast.FuncDef):
            sh = set(shadow)
            ft = n.decl.type
            if isinstance(ft, c_ast.FuncDecl) and ft.args:
                for p in ft.args.params:
                    if isinstance(p, c_ast.Decl) and p.name:
                        sh.add(p.name)
            self.run(n.body, frozenset(sh))
            return
        if isinstance(n, c_ast.Compound):
            sh = set(shadow)
            for it in n.block_items or []:
                if isinstance(it, c_ast.Decl) and it.name:
                    if it.init is not None:
                        self.run(it.init, frozenset(sh))
                    sh.add(it.name)
                    self.run_type(it.type, frozenset(sh))
                else:
                    self.run(it, frozenset(sh))
            return
        if isinstance(n, c_ast.For) and isinstance(n.init, c_ast.DeclList):
            sh = set(shadow)
            for d in n.init.decls:
                if d.init is not None:
                    self.run(d.init, frozenset(sh))
                sh.add(d.name)
            for c in (n.cond, n.next, n.stmt):
                self.run(c, frozenset(sh))
            return
        if isinstance(n, c_ast.StructRef):
            self.run(n.name, shadow)
            return
        for name in n.__slots__:
            if name in ('coord', '__weakref__'):
                continue
            v = getattr(n, name, None)
            if isinstance(v, c_ast.Node):
                self.run(v, shadow)
            elif isinstance(v, list):
                for it in v:
                    if isinstance(it, c_ast.Node):
                        self.run(it, shadow)

    def run_type(self, t, shadow):
        # array dimensions may use file-scope names
        while t is not None and hasattr(t, 'type'):
            if isinstance(t, c_ast.ArrayDecl) and t.dim is not None:
                self.run(t.dim, shadow)
            t = t.type


def split(ast, unit, maxlines, outdir, counter):
    """cut a unit too big for one CMS file of assembler into parts: its
    static functions and variables become external (renamed CYnnnnn),
    each part defines some of the functions and declares the rest"""
    def is_own(n):
        f = str(n.coord.file) if n.coord is not None else ''
        if os.path.basename(f) == unit + '.c':
            return True
        if 'gcclib31' in f:
            return False
        if isinstance(n, c_ast.FuncDef):        # out-of-line code from .inc files
            return 'inline' not in (n.decl.funcspec or [])
        if isinstance(n, c_ast.Decl) and 'static' in (n.storage or []) and \
                not isinstance(n.type, c_ast.FuncDecl):
            return True                         # one copy of static data
        return False
    own = [n for n in ast.ext if is_own(n)]
    ownids = set(id(n) for n in own)
    gen = c_generator.CGenerator()
    names = {}
    for n in own:
        d = n.decl if isinstance(n, c_ast.FuncDef) else n
        if isinstance(d, c_ast.Decl) and d.name and 'static' in (d.storage or []):
            if isinstance(n, c_ast.FuncDef) or not isinstance(d.type, c_ast.FuncDecl):
                names[d.name] = 'CY%05d' % counter[0]
                counter[0] += 1
    # static prototypes of those functions are renamed too
    for n in ast.ext:
        if isinstance(n, c_ast.Decl) and n.name in names:
            n.storage = [x for x in n.storage if x != 'static']
            n.funcspec = [x for x in n.funcspec if x != 'inline']
            n.name = names[n.name]
            declname_set(n.type, n.name)
        elif isinstance(n, c_ast.FuncDef) and n.decl.name in names:
            d = n.decl
            d.storage = [x for x in d.storage if x != 'static']
            d.funcspec = [x for x in d.funcspec if x != 'inline']
            d.name = names[d.name]
            declname_set(d.type, d.name)
    Renamer(names).run(ast)
    for n in ast.ext:
        if isinstance(n, c_ast.FuncDef):
            Renamer(names).run(n)
    # partition the unit's function definitions by size
    # and by external symbols: the assembler takes about 400 ESD entries
    funcs = [n for n in own if isinstance(n, c_ast.FuncDef)]
    globs = set()
    for n in ast.ext:
        if isinstance(n, c_ast.FuncDef):
            globs.add(n.decl.name)
        elif isinstance(n, c_ast.Decl) and n.name and 'typedef' not in (n.storage or []):
            if 'static' not in (n.storage or []) or isinstance(n.type, c_ast.FuncDecl):
                globs.add(n.name)
    statvars = set(names.values())
    budget = int(os.environ.get('XFMAXESD', '330'))
    parts, cur, size, syms = [], [], 0, set()
    for f in funcs:
        l = gen.visit(f).count('\n')
        nm = Names()
        nm.visit(f.body)
        fs = {x for x in nm.ids if x in globs} | {f.decl.name}
        if cur and (size + l > maxlines or len(syms | fs) > budget):
            parts.append(cur)
            cur, size, syms = [], 0, set()
        cur.append(f)
        size += l
        syms |= fs
    if cur:
        parts.append(cur)
    # a single function that alone calls too many external functions (the
    # VM's run(): one call per outlined handler) calls those through a
    # table, which each part fills for its own functions
    import copy as _copy
    extra_defs = {}             # part index -> items to append
    extra_top = {}              # part index -> items to insert before defs
    where = {}
    for k, part in enumerate(parts):
        for f in part:
            where[f.decl.name] = k
    fdef = {f.decl.name: f for f in funcs}
    for k, part in enumerate(parts):
        if len(part) != 1:
            continue
        g = part[0]
        nm = Names()
        nm.visit(g.body)
        callees = sorted(x for x in nm.ids if x in where and where[x] != k)
        if len(callees) + len([x for x in nm.ids if x in globs]) <= budget:
            continue
        tbl = 'CY%05d' % counter[0]
        flag = 'CY%05d' % (counter[0] + 1)
        counter[0] += 2
        idx = {c: i for i, c in enumerate(callees)}

        def fptr(name):
            ft = _copy.deepcopy(fdef[name].decl.type)
            t = ft.type
            while not isinstance(t, c_ast.TypeDecl):
                t = t.type
            t.declname = None
            return c_ast.Typename(None, [], None, c_ast.PtrDecl([], ft))

        def ref(name):
            return c_ast.Cast(fptr(name), c_ast.ArrayRef(c_ast.ID(tbl), c_ast.Constant('int', str(idx[name]))))
        replace_ids(g.body, {c: (lambda c=c: ref(c)) for c in callees})
        regs = {}
        for c in callees:
            regs.setdefault(where[c], []).append(c)
        vptr = lambda: c_ast.Typename(None, [], None, c_ast.PtrDecl([], c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['void']))))
        top_g = [c_ast.Decl(tbl, [], [], [], [], c_ast.ArrayDecl(c_ast.PtrDecl([], c_ast.TypeDecl(tbl, [], None, c_ast.IdentifierType(['void']))),
                                                                 c_ast.Constant('int', str(len(callees))), []), None, None),
                 c_ast.Decl(flag, [], [], [], [], c_ast.TypeDecl(flag, [], None, c_ast.IdentifierType(['int'])), None, None)]
        calls = []
        for j, cs in sorted(regs.items()):
            rn = 'CY%05d' % counter[0]
            counter[0] += 1
            body = [c_ast.Assignment('=', c_ast.ArrayRef(c_ast.ID(tbl), c_ast.Constant('int', str(idx[c]))),
                                     c_ast.Cast(vptr(), c_ast.ID(c))) for c in cs]
            rdecl = c_ast.Decl(rn, [], [], [], [], c_ast.FuncDecl(c_ast.ParamList([c_ast.Typename(None, [], None, c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['void'])))]),
                                                                  c_ast.TypeDecl(rn, [], None, c_ast.IdentifierType(['void']))), None, None)
            ext_tbl = c_ast.Decl(tbl, [], [], ['extern'], [], c_ast.ArrayDecl(c_ast.PtrDecl([], c_ast.TypeDecl(tbl, [], None, c_ast.IdentifierType(['void']))), None, []), None, None)
            extra_defs.setdefault(j, []).extend([ext_tbl, c_ast.FuncDef(_copy.deepcopy(rdecl), None, c_ast.Compound(body))])
            top_g.append(rdecl)
            calls.append(c_ast.FuncCall(c_ast.ID(rn), c_ast.ExprList([])))
        init = c_ast.If(c_ast.UnaryOp('!', c_ast.ID(flag)),
                        c_ast.Compound([c_ast.Assignment('=', c_ast.ID(flag), c_ast.Constant('int', '1'))] + calls), None)
        g.body.block_items = [init] + (g.body.block_items or [])
        extra_top.setdefault(k, []).extend(top_g)
    import copy
    outs = []
    for k, part in enumerate(parts):
        pid = set(id(f) for f in part)
        items = []
        roots = set()
        for n in ast.ext:
            if isinstance(n, c_ast.FuncDef) and id(n) in ownids:
                if id(n) in pid:
                    items.append(n)
                    roots.add(id(n))
                else:
                    d = copy.copy(n.decl)
                    d.storage = [x for x in (d.storage or []) if x not in ('static', 'extern')]
                    d.funcspec = [x for x in (d.funcspec or []) if x != 'inline']
                    d.coord = n.coord
                    items.append(d)
            elif isinstance(n, c_ast.Decl) and id(n) in ownids and n.name and \
                    not isinstance(n.type, c_ast.FuncDecl) and 'extern' not in (n.storage or []) \
                    and 'typedef' not in (n.storage or []):
                if k == 0:
                    d = copy.copy(n)
                    d.storage = [x for x in (n.storage or []) if x != 'static']
                    items.append(d)
                    roots.add(id(d))
                else:
                    d = copy.copy(n)
                    d.storage = ['extern'] + [x for x in (n.storage or []) if x not in ('static', 'extern')]
                    d.init = None
                    items.append(d)
            else:
                items.append(n)
        # registration functions and the table go before this part's
        # first definition of the unit's own
        first = next((i for i, n in enumerate(items) if id(n) in pid), len(items))
        items[first:first] = extra_top.get(k, [])
        items += extra_defs.get(k, [])
        for n in extra_top.get(k, []) + extra_defs.get(k, []):
            roots.add(id(n))
        a = c_ast.FileAST(items)
        prune(a, unit + '.c', roots)
        pname = unit if k == 0 else (unit[:6] + 'P%d' % k)
        with open(os.path.join(outdir, pname + '.c'), 'w', encoding='latin-1') as f:
            f.write(PROLOGUE + gen.visit(a))
        outs.append(pname)
    return outs, len(names)


def main():
    stage, unit, outdir = sys.argv[1:4]
    src = subprocess.run(CPP + ['-I' + stage, '-I' + os.path.join(HERE, 'inc'),
                                '-I' + os.path.join(HERE, '..', '..', 'gcclib31', 'src'),
                                os.path.join(stage, unit + '.c')],
                         capture_output=True, text=True, encoding='latin-1')
    if src.returncode:
        raise SystemExit(src.stderr)
    ast = c_parser.CParser().parse(src.stdout, unit + '.c')
    kept = prune(ast, unit + '.c')
    ty = Types(ast)
    xf = Xform(ty)
    for i, n in enumerate(ast.ext):
        if isinstance(n, c_ast.FuncDef):
            ast.ext[i] = xf.x(n, [])
        elif isinstance(n, c_ast.Decl) and n.init is not None and n.type is not None \
                and not isinstance(n.type, c_ast.FuncDecl):
            pass                     # static initialisers are constant-folded
    packed = pack_tables(ast, ty)
    if packed:
        print('%s: %d tables packed' % (unit, packed))
    text = c_generator.CGenerator().visit(ast)
    maxl = int(os.environ.get('XFMAXLINES', '15000'))
    pf = os.path.join(outdir, unit + '.parts')
    nmx = Names()
    nmx.visit(ast)
    ext_est = len([x for x in nmx.ids if x in ty.globals])
    if text.count('\n') > maxl * 1.3 or ext_est > int(os.environ.get('XFMAXESD', '330')):
        cf = os.path.join(outdir, 'split.counter')
        counter = [int(open(cf).read()) if os.path.exists(cf) else 0]
        parts, nren = split(ast, unit, maxl, outdir, counter)
        open(cf, 'w').write(str(counter[0]))
        open(pf, 'w').write(' '.join(parts) + '\n')
        print('%s: %d items kept, %d rewritten, %d untyped, %d lines; split in %d (%d statics made external)'
              % (unit, kept, xf.count, xf.unknown, text.count('\n'), len(parts), nren))
        return
    if os.path.exists(pf):
        os.remove(pf)
    with open(os.path.join(outdir, unit + '.c'), 'w', encoding='latin-1') as f:
        f.write(PROLOGUE + text)
    print('%s: %d items kept, %d rewritten, %d untyped, %d lines' % (unit, kept, xf.count, xf.unknown, text.count('\n')))


if __name__ == '__main__':
    main()
