#!/usr/bin/env python3
"""M8.2 xform: rewrite a staged cREXX unit so GCC380 can compile it.

    xform.py STAGE UNIT OUTDIR    -> OUTDIR/UNIT.c (preprocessed, rewritten)

GCC380's i370 back end has no 64-bit add: every long long '+' (and every
'-' of a constant, which GCC folds into an add) ends in an internal
compiler error.  Its 64-bit subtract, shifts, compares and the libcalls
work.  So the unit is preprocessed on the PC, parsed (pycparser), typed,
and every 64-bit +, -, +=, -=, ++ and -- becomes a call to CRXLGCC C's
crxadd64 / crxsub64 / crxadt64 / crxinc64, which work in 32-bit halves.

The output is one self-contained C file: the unit with only the
declarations it uses (the headers are pruned to what is reachable from
the unit's own definitions)."""
import os
import re
import subprocess
import sys

from pycparser import c_ast, c_generator, c_parser

HERE = os.path.dirname(os.path.abspath(__file__))


_orig_designator = c_parser.CParser._parse_designator


def _parse_designator(self):
    # pycparser keeps [ID] and .ID alike and prints both as .ID:
    # wrap an index so the generator prints [ID]
    if self._peek_type() == "LBRACKET":
        return c_ast.ExprList([_orig_designator(self)])
    return _orig_designator(self)


c_parser.CParser._parse_designator = _parse_designator

PROLOGUE = '''/* M8.2: generated by xform.py from the staged unit -- do not edit */
#define __crx_crab() ({GCCCRAB *__t; __asm__("L %0,72(13)" : "=d" (__t)); __t;})
long long crxadd64(long long a, long long b);
long long crxsub64(long long a, long long b);
long long crxadt64(long long *p, long long b);
long long crxinc64(long long *p, long long d, int post);
'''
HELPERS = ('crxadd64', 'crxsub64', 'crxadt64', 'crxinc64')

INT = {'char': 8, 'short': 16, 'int': 32, 'long': 32, '_Bool': 8}


class Types:
    def __init__(self, ast):
        self.typedefs = {}
        self.tags = {}
        self.globals = {}
        self.enumconst = set()
        LL = c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['long', 'long']))
        for h in HELPERS:
            self.globals[h] = c_ast.FuncDecl(None, LL)
        for ext in ast.ext:
            self.note(ext)

    def note(self, n):
        """record typedefs, tags and global names from a declaration"""
        if isinstance(n, c_ast.Typedef):
            self.typedefs[n.name] = n.type
            self.tags_in(n.type)
        elif isinstance(n, c_ast.Decl):
            if n.name:
                self.globals[n.name] = n.type
            self.tags_in(n.type)
        elif isinstance(n, c_ast.FuncDef):
            self.globals[n.decl.name] = n.decl.type

    def tags_in(self, t):
        while isinstance(t, (c_ast.PtrDecl, c_ast.ArrayDecl, c_ast.TypeDecl, c_ast.FuncDecl)):
            t = t.type
        if isinstance(t, (c_ast.Struct, c_ast.Union)) and t.decls is not None and t.name:
            self.tags[(type(t).__name__, t.name)] = t
        if isinstance(t, (c_ast.Struct, c_ast.Union)) and t.decls:
            for d in t.decls:
                self.tags_in(d.type)
        if isinstance(t, c_ast.Enum) and t.values:
            for e in t.values.enumerators:
                self.enumconst.add(e.name)

    # ---- simplified types: ('int', bits, unsigned) ('float',) ('ptr', T)
    #      ('struct', node) ('func', T) ('void',) or None (unknown)
    def resolve(self, t, depth=0):
        if t is None or depth > 40:
            return None
        if isinstance(t, c_ast.Typename) or isinstance(t, c_ast.Decl):
            return self.resolve(t.type, depth + 1)
        if isinstance(t, c_ast.TypeDecl):
            return self.resolve(t.type, depth + 1)
        if isinstance(t, c_ast.PtrDecl):
            return ('ptr', t.type)
        if isinstance(t, c_ast.ArrayDecl):
            return ('ptr', t.type)
        if isinstance(t, c_ast.FuncDecl):
            return ('func', t.type)
        if isinstance(t, (c_ast.Struct, c_ast.Union)):
            if t.decls is None:
                t = self.tags.get((type(t).__name__, t.name), t)
            return ('struct', t)
        if isinstance(t, c_ast.Enum):
            return ('int', 32, False)
        if isinstance(t, c_ast.IdentifierType):
            names = [x for x in t.names if x not in ('signed', 'const', 'volatile')]
            uns = 'unsigned' in t.names
            names = [x for x in names if x != 'unsigned']
            if not names:
                return ('int', 32, uns)
            if 'double' in names or 'float' in names:
                return ('float',)
            if names == ['void']:
                return ('void',)
            if names.count('long') == 2:
                return ('int', 64, uns)
            if len(names) == 1 and names[0] in self.typedefs:
                return self.resolve(self.typedefs[names[0]], depth + 1)
            for k in ('char', 'short', '_Bool'):
                if k in names:
                    return ('int', INT[k], uns)
            if 'long' in names or 'int' in names:
                return ('int', 32, uns)
            if len(names) == 1 and names[0] == '__builtin_va_list':
                return ('ptr', None)
            return None
        return None

    def field(self, st, name):
        if not st or st[0] != 'struct':
            return None
        node = st[1]
        if not isinstance(node, (c_ast.Struct, c_ast.Union)) or node.decls is None:
            return None
        for d in node.decls:
            if d.name == name:
                return self.resolve(d.type)
            if d.name is None:                       # anonymous member
                r = self.field(self.resolve(d.type), name)
                if r:
                    return r
        return None


def arith(a, b):
    """usual arithmetic conversions"""
    if not a or not b:
        return None
    if a[0] == 'float' or b[0] == 'float':
        return ('float',) if a[0] in ('float', 'int') and b[0] in ('float', 'int') else None
    if a[0] == 'int' and b[0] == 'int':
        if a[1] == 64 or b[1] == 64:
            uns = (a[1] == 64 and a[2]) or (b[1] == 64 and b[2])
            return ('int', 64, uns)
        return ('int', 32, a[2] and a[1] == 32 or b[2] and b[1] == 32)
    return None


def is64(t):
    return t is not None and t[0] == 'int' and t[1] == 64


def const_type(c):
    if c.type in ('char',):
        return ('int', 32, False)
    if c.type in ('float', 'double'):
        return ('float',)
    v = c.value.lower()
    if 'll' in v:
        return ('int', 64, 'u' in v)
    try:
        n = int(v.rstrip('ul'), 0) if not re.match(r'0[0-7]+$', v.rstrip('ul')) else int(v.rstrip('ul'), 8)
    except ValueError:
        return ('int', 32, False)
    if n > 0xFFFFFFFF or (n > 0x7FFFFFFF and v.rstrip('ul').isdigit() and 'u' not in v):
        return ('int', 64, 'u' in v)
    return ('int', 32, 'u' in v or n > 0x7FFFFFFF)


LLT = c_ast.Typename(None, [], None, c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['long', 'long'])))
ULLT = c_ast.Typename(None, [], None, c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['unsigned', 'long', 'long'])))
LLP = c_ast.Typename(None, [], None, c_ast.PtrDecl([], c_ast.TypeDecl(None, [], None, c_ast.IdentifierType(['long', 'long']))))


def call(name, *args):
    return c_ast.FuncCall(c_ast.ID(name), c_ast.ExprList(list(args)))


def cast(t, e):
    return c_ast.Cast(t, e)


class Xform:
    def __init__(self, ty):
        self.ty = ty
        self.count = 0
        self.unknown = 0

    # ---- scopes
    def lookup(self, scopes, name):
        for s in reversed(scopes):
            if name in s:
                return self.ty.resolve(s[name])
        if name in self.ty.globals:
            return self.ty.resolve(self.ty.globals[name])
        if name in self.ty.enumconst:
            return ('int', 32, False)
        return None

    def typeof(self, e, sc):
        T = self.ty
        if isinstance(e, c_ast.Constant):
            if e.type == 'string':
                return ('ptr', None)
            return const_type(e)
        if isinstance(e, c_ast.ID):
            return self.lookup(sc, e.name)
        if isinstance(e, c_ast.Cast):
            return T.resolve(e.to_type)
        if isinstance(e, c_ast.UnaryOp):
            if e.op == '&':
                return ('ptr', None)
            if e.op == '*':
                p = self.typeof(e.expr, sc)
                return T.resolve(p[1]) if p and p[0] == 'ptr' and p[1] is not None else None
            if e.op in ('sizeof', '_Alignof'):
                return ('int', 32, True)
            if e.op == '!':
                return ('int', 32, False)
            t = self.typeof(e.expr, sc)
            if e.op in ('-', '+', '~') and t and t[0] == 'int' and t[1] < 32:
                return ('int', 32, False)
            return t
        if isinstance(e, c_ast.BinaryOp):
            if e.op in ('<', '>', '<=', '>=', '==', '!=', '&&', '||'):
                return ('int', 32, False)
            a, b = self.typeof(e.left, sc), self.typeof(e.right, sc)
            if e.op in ('<<', '>>'):
                return a if a and a[0] == 'int' and a[1] >= 32 else ('int', 32, False) if a else None
            if e.op in ('+', '-') and a and a[0] == 'ptr':
                return ('int', 32, False) if e.op == '-' and b and b[0] == 'ptr' else a
            if e.op == '+' and b and b[0] == 'ptr':
                return b
            return arith(a, b)
        if isinstance(e, c_ast.Assignment):
            return self.typeof(e.lvalue, sc)
        if isinstance(e, c_ast.TernaryOp):
            a, b = self.typeof(e.iftrue, sc), self.typeof(e.iffalse, sc)
            if a and a[0] == 'int' and b and b[0] == 'int':
                return arith(a, b)
            return a or b
        if isinstance(e, c_ast.FuncCall):
            f = self.typeof(e.name, sc)
            if f and f[0] == 'ptr' and f[1] is not None:
                f = T.resolve(f[1])
            if f and f[0] == 'func':
                return T.resolve(f[1])
            return None
        if isinstance(e, c_ast.StructRef):
            s = self.typeof(e.name, sc)
            if e.type == '->':
                s = T.resolve(s[1]) if s and s[0] == 'ptr' and s[1] is not None else None
            return T.field(s, e.field.name)
        if isinstance(e, c_ast.ArrayRef):
            p = self.typeof(e.name, sc)
            if p and p[0] == 'ptr' and p[1] is not None:
                return T.resolve(p[1])
            q = self.typeof(e.subscript, sc)        # i[a]
            if q and q[0] == 'ptr' and q[1] is not None:
                return T.resolve(q[1])
            return None
        if isinstance(e, c_ast.ExprList):
            return self.typeof(e.exprs[-1], sc) if e.exprs else None
        if isinstance(e, c_ast.CompoundLiteral):
            return T.resolve(e.type)
        return None

    # ---- rewriting
    def x(self, n, sc):
        """rewrite node n (in place where possible); returns the node"""
        if n is None:
            return None
        if isinstance(n, c_ast.FuncDef):
            s = {}
            ft = n.decl.type
            if isinstance(ft, c_ast.FuncDecl) and ft.args:
                for p in ft.args.params:
                    if isinstance(p, c_ast.Decl) and p.name:
                        s[p.name] = p.type
            n.body = self.x(n.body, sc + [s])
            return n
        if isinstance(n, c_ast.Compound):
            s = {}
            sc2 = sc + [s]
            items = n.block_items or []
            for i, it in enumerate(items):
                if isinstance(it, c_ast.Decl):
                    if it.name:
                        s[it.name] = it.type
                    self.ty.tags_in(it.type)
                    if it.init is not None:
                        it.init = self.x(it.init, sc2)
                elif isinstance(it, c_ast.Typedef):
                    self.ty.typedefs[it.name] = it.type
                    self.ty.tags_in(it.type)
                else:
                    items[i] = self.x(it, sc2)
            return n
        if isinstance(n, c_ast.For):
            s = {}
            sc2 = sc + [s]
            if isinstance(n.init, c_ast.DeclList):
                for d in n.init.decls:
                    s[d.name] = d.type
                    if d.init is not None:
                        d.init = self.x(d.init, sc2)
            else:
                n.init = self.x(n.init, sc2)
            n.cond = self.x(n.cond, sc2)
            n.next = self.x(n.next, sc2)
            n.stmt = self.x(n.stmt, sc2)
            return n
        if isinstance(n, c_ast.Decl):
            if n.init is not None:
                n.init = self.x(n.init, sc)
            return n
        # generic: rewrite children first
        for name in n.__slots__:
            if name in ('coord', '__weakref__'):
                continue
            v = getattr(n, name, None)
            if isinstance(v, c_ast.Node):
                if isinstance(n, (c_ast.Cast, c_ast.Typename)) and name in ('to_type', 'type'):
                    continue
                if isinstance(n, c_ast.UnaryOp) and n.op in ('sizeof', '_Alignof'):
                    continue
                if isinstance(n, c_ast.StructRef) and name == 'field':
                    continue
                setattr(n, name, self.x(v, sc))
            elif isinstance(v, list):
                for i, it in enumerate(v):
                    if isinstance(it, c_ast.Node):
                        v[i] = self.x(it, sc)
        return self.rewrite(n, sc)

    def rewrite(self, n, sc):
        if isinstance(n, c_ast.BinaryOp) and n.op in ('+', '-'):
            t = self.typeof(n, sc)
            if t is None:
                self.unknown += 1
                if os.environ.get('XFDEBUG'):
                    print('unknown type:', n.coord, c_generator.CGenerator().visit(n)[:100])
            if is64(t):
                self.count += 1
                r = call('crxadd64' if n.op == '+' else 'crxsub64', cast(LLT, n.left), cast(LLT, n.right))
                return cast(ULLT, r) if t[2] else r
        if isinstance(n, c_ast.Assignment) and n.op in ('+=', '-='):
            lt = self.typeof(n.lvalue, sc)
            rt = self.typeof(n.rvalue, sc)
            if is64(lt) and (rt is None or rt[0] == 'int'):
                self.count += 1
                rv = cast(LLT, n.rvalue)
                if n.op == '-=':
                    rv = c_ast.UnaryOp('-', rv)
                r = call('crxadt64', cast(LLP, c_ast.UnaryOp('&', n.lvalue)), rv)
                return cast(ULLT, r) if lt[2] else r
            if lt and lt[0] == 'int' and is64(rt):
                self.count += 1        # int += long long: computed in 64 bits
                op = 'crxadd64' if n.op == '+=' else 'crxsub64'
                return c_ast.Assignment('=', n.lvalue, call(op, cast(LLT, n.lvalue), cast(LLT, n.rvalue)))
        if isinstance(n, c_ast.UnaryOp) and n.op in ('++', '--', 'p++', 'p--'):
            t = self.typeof(n.expr, sc)
            if is64(t):
                self.count += 1
                d = c_ast.Constant('int', '1' if '+' in n.op else '-1')
                r = call('crxinc64', cast(LLP, c_ast.UnaryOp('&', n.expr)), cast(LLT, d),
                         c_ast.Constant('int', '1' if n.op.startswith('p') else '0'))
                return cast(ULLT, r) if t[2] else r
        return n


class Names(c_ast.NodeVisitor):
    """identifiers, type names and tags a node uses"""
    def __init__(self):
        self.ids = set()
        self.tags = set()

    def visit_ID(self, n):
        self.ids.add(n.name)

    def visit_IdentifierType(self, n):
        for x in n.names:
            self.ids.add(x)

    def visit_Struct(self, n):
        if n.name:
            self.tags.add(('Struct', n.name))
        self.generic_visit(n)

    def visit_Union(self, n):
        if n.name:
            self.tags.add(('Union', n.name))
        self.generic_visit(n)

    def visit_Enum(self, n):
        if n.name:
            self.tags.add(('Enum', n.name))
        self.generic_visit(n)

    def visit_StructRef(self, n):
        self.visit(n.name)               # not the field name

    def visit_NamedInitializer(self, n):
        self.visit(n.expr)


def defines(n):
    """names, tags and enum constants a top-level item defines"""
    names, tags = set(), set()
    if isinstance(n, c_ast.FuncDef):
        names.add(n.decl.name)
        return names, tags
    if isinstance(n, (c_ast.Typedef, c_ast.Decl)) and n.name:
        names.add(n.name)
    t = n.type if hasattr(n, 'type') else None
    while isinstance(t, (c_ast.PtrDecl, c_ast.ArrayDecl, c_ast.TypeDecl, c_ast.FuncDecl)):
        t = t.type
    if isinstance(t, (c_ast.Struct, c_ast.Union, c_ast.Enum)):
        if t.name:
            tags.add((type(t).__name__, t.name))
        if isinstance(t, c_ast.Enum) and t.values:
            for e in t.values.enumerators:
                names.add(e.name)
    return names, tags


def prune(ast, unitfile):
    """keep the unit's own items and what they reach"""
    items = ast.ext
    info = []
    for n in items:
        nm = Names()
        nm.visit(n)
        d, dt = defines(n)
        own = n.coord is not None and os.path.basename(str(n.coord.file)) == unitfile
        info.append((n, own, d, dt, nm.ids, nm.tags))
    keep = [False] * len(items)
    need_ids, need_tags = {'GCCCRAB'}, set()
    by_name, by_tag = {}, {}
    for i, (n, own, d, dt, ids, tags) in enumerate(info):
        for x in d:
            by_name.setdefault(x, []).append(i)
        for x in dt:
            by_tag.setdefault(x, []).append(i)
    work = [i for i, inf in enumerate(info) if inf[1]]
    for x in need_ids:
        work += by_name.get(x, [])
    while work:
        i = work.pop()
        if keep[i]:
            continue
        keep[i] = True
        n, own, d, dt, ids, tags = info[i]
        for x in ids:
            work += [j for j in by_name.get(x, []) if not keep[j]]
        for x in tags:
            work += [j for j in by_tag.get(x, []) if not keep[j]]
    out = []
    for i, n in enumerate(items):
        if keep[i] and not (isinstance(n, c_ast.Decl) and n.name == '__crx_crab'):
            out.append(n)
    ast.ext = out
    return sum(keep)


CPP = ['s390x-linux-gnu-gcc', '-E', '-m31', '-undef', '-nostdinc', '-D__CMS__', '-D__GNUC__=3',
       '-D__GNUC_MINOR__=2', '-D__i370__', '-D__CHAR_UNSIGNED__', '-D__attribute__(x)=',
       '-D__inline__=inline', '-D__inline=inline', '-D__restrict__=', '-D__restrict=',
       '-D__extension__=', '-D__asm__(x)=']


def main():
    stage, unit, outdir = sys.argv[1:4]
    src = subprocess.run(CPP + ['-I' + stage, '-I' + os.path.join(HERE, 'inc'),
                                '-I' + os.path.join(HERE, '..', '..', 'gcclib31', 'src'),
                                os.path.join(stage, unit + '.c')],
                         capture_output=True, text=True, encoding='latin-1')
    if src.returncode:
        raise SystemExit(src.stderr)
    ast = c_parser.CParser().parse(src.stdout, unit + '.c')
    kept = prune(ast, unit + '.c')
    ty = Types(ast)
    xf = Xform(ty)
    for i, n in enumerate(ast.ext):
        if isinstance(n, c_ast.FuncDef):
            ast.ext[i] = xf.x(n, [])
        elif isinstance(n, c_ast.Decl) and n.init is not None and n.type is not None \
                and not isinstance(n.type, c_ast.FuncDecl):
            pass                     # static initialisers are constant-folded
    text = c_generator.CGenerator().visit(ast)
    with open(os.path.join(outdir, unit + '.c'), 'w', encoding='latin-1') as f:
        f.write(PROLOGUE + text)
    print('%s: %d items kept, %d rewritten, %d untyped, %d lines' % (unit, kept, xf.count, xf.unknown, text.count('\n')))


if __name__ == '__main__':
    main()
