#!/usr/bin/env python3
"""Generate a probe deck that measures which ESA/390 mnemonics CE's
assembler knows.

XAOPS.MACRO exists because CE's assembler predates 370-XA.  The obvious
question -- is the macro list complete? -- was answered twice by guessing and
wrong both times, so this answers it by measurement instead.

Method.  Every mnemonic Hercules marks as available in ESA/390 mode is
emitted as a bare statement with no operands at all.  Operand syntax does not
matter, because the only message being counted is

    IFO078 UNDEFINED OP CODE

A mnemonic the assembler knows but whose operands are missing produces some
other diagnostic, which is ignored.  That turns 351 instructions into one
assembly and one grep, with no need to write valid operands for formats
nobody is going to use.

The GLOBAL MACLIB list must be CLEARED before assembling the result.  With
XALIB active a name matching a macro would resolve quietly and look like an
instruction the assembler knows -- the same confusion that made the first
z390 validation worthless.

    python3 mkprobe.py path/to/hercules/opcode.c > XAFULL.ASSEMBLE

Then, on CMS:

    GLOBAL MACLIB
    ASSEMBLE XAFULL (DISK
"""
import re
import sys

# GENx370x390x900 and GENx___x390x900 are available in ESA/390 mode.
# GENx___x___x900 is z/Architecture only and is deliberately excluded.
ENTRY = re.compile(r'GENx(?:370|___)x390x\w+\s*\(\s*\w+\s*,\s*(\w+)\s*,\s*"([^"]+)"')

# HLASM mnemonics are at most five characters; anything else in the table is
# a placeholder rather than a real operation code.
MNEMONIC = re.compile(r'[A-Z][A-Z0-9]{0,4}$')

# Names that are assembler statements rather than instructions would be
# processed as such and never reported as undefined, so they cannot be
# measured this way and are excluded rather than silently miscounted.
DIRECTIVES = {
    'CCW', 'CNOP', 'COPY', 'CSECT', 'DC', 'DROP', 'DS', 'DSECT', 'EJECT',
    'END', 'ENTRY', 'EQU', 'EXTRN', 'ICTL', 'ISEQ', 'LTORG', 'MEND',
    'MEXIT', 'MNOTE', 'ORG', 'POP', 'PRINT', 'PUSH', 'REPRO', 'SPACE',
    'START', 'TITLE', 'USING', 'WXTRN',
}


def mnemonics(source):
    found = {}
    for fmt, name in ENTRY.findall(source):
        name = name.strip()
        if MNEMONIC.match(name) and name not in DIRECTIVES and name not in found:
            found[name] = fmt
    return dict(sorted(found.items()))


def card(text=''):
    """A comment box line, exactly 71 columns wide.

    Column 72 is the continuation column and column 73 onward carries change
    markers, so a comment one character too long turns the next line into a
    continuation.  That has already cost this project a cycle once.
    """
    assert len(text) <= 67, (len(text), text)
    return '* ' + text + ' ' * (68 - len(text)) + '*'


def deck(found):
    bar = '*' + '-' * 69 + '*'
    out = [bar,
           card('XAFULL  -  GENERATED BY tools/mkprobe.py.  DO NOT EDIT.'),
           card(),
           card('EVERY MNEMONIC HERCULES MARKS AVAILABLE IN ESA/390 MODE, EMITTED'),
           card('WITH NO OPERANDS.  COUNT ONLY IFO078 UNDEFINED OP CODE; EVERY'),
           card('OTHER DIAGNOSTIC MEANS THE ASSEMBLER KNEW THE MNEMONIC AND'),
           card('OBJECTED TO THE MISSING OPERANDS, WHICH IS A PASS.'),
           card(),
           card('ASSEMBLE WITH THE GLOBAL MACLIB LIST CLEARED.'),
           bar,
           'XAFULL   CSECT']

    # Controls.  If any of these is reported undefined then the probe itself
    # is broken and no other line in the result means anything.
    out += [card('CONTROLS -- ALL S/370, ALL MUST BE ACCEPTED').replace('*', '*', 1),
            '         LR    1,2',
            '         L     1,0(0,2)',
            '         LCTL  1,1,0(2)',
            '         ISK   1,2',
            '         LRA   1,0(0,2)',
            '         SVC   0']

    for name in found:
        out.append('         ' + name)

    out += ['         BR    14', '         END']
    return out


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else 'opcode.c'
    found = mnemonics(open(path).read())
    print('\n'.join(deck(found)))
    print('* %d mnemonics probed' % len(found), file=sys.stderr)


if __name__ == '__main__':
    main()
