#!/usr/bin/env python3
"""Per-module conversion status, computed rather than hand-maintained.

The project has registers for risks, issues and milestones but no view of
where each CP module stands. A hand-written table would go stale on the next
deck, so this derives the state from four sources:

  * the nucleus load list          maintenance/files/194/CPLOAD.EXEC
  * what ASMDMK assembles          maintenance/files/194/ASMDMK.EXEC
  * which modules we have changed   arch/31bit/updates/*.AUXLCL
  * which modules the PSA rename    a scan of source/cp for the renamed
    breaks                          symbols

    python3 status.py /path/to/vmce [--all]

Baseline: `ASMDMK DMKHRC` assembled 186 of 186 with 185 clean on 27 September
(docs/21-NUCLEUS-GAP.md). The single exception is recorded below rather than
re-derived, because it is a property of CE's site configuration and not of
any module's source.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UPDATES = os.path.join(HERE, '..', 'updates')

# Symbols the PSA lowcore change renamed.  A module referencing any of them
# no longer assembles until it is dealt with.  docs/19-M1-STEP2.md.
RENAMED = ('INTTIO', 'CHANID', 'IOELPNTR', 'ECSWLOG', 'ECSWBYT3')

# Sites where a renamed symbol is a displacement into a GUEST's page 0, not
# into CP's own lowcore.  Guests stay S/370-mode through M4, so these need a
# symbol swap and no semantic change at all.  I-36.
GUEST_PSA = {'DMKDSP': 'INTTIO-PSA-1',
             'DMKPRV': 'CHANID-PSA',
             'DMKCCH': 'ECSWLOG-PSA'}

# Severity-4 MNOTEs for 3375/3390 in CE's site configuration, not a source
# defect and the TEXT deck is still produced.  I-34.
BASELINE_WARN = {'DMKRIO': 'RDEVICE 3375/3390 UNSUPPORTED DEVICE TYPE, sev 4'}

# What each broken module actually needs, from reading its sites.
NEEDS = {
    'DMKIOT': 'convert: 10 INTTIO sites, interrupt entry -- M1 step 5',
    'DMKDSP': 'guest-PSA symbol swap (G370TIO), no semantic change',
    'DMKPRV': 'guest-PSA symbol swap (S370CHID), STIDC simulation',
    'DMKCCH': 'guest-PSA swap plus 13 channel-logout sites -- R-03',
    'DMKIOG': 'channel logout: CHANID x3, ECSWLOG x2, IOELPNTR x1 -- R-03',
    'DMKEIG': 'channel logout: IOELPNTR x2 -- R-03',
    'DMKCKP': '4 INTTIO compared against device addresses -- M3a',
    'DMKDMP': '3 INTTIO compared against device addresses -- M3a',
    'DMKVMI': '1 INTTIO compared against a device address -- M3a',
}


def listed(path, pattern):
    return [m.group(1) for m in re.finditer(pattern, open(path).read())]


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else '/home/claude/vmce'
    M = os.path.join(root, 'maintenance', 'files', '194')
    src = os.path.join(root, 'source', 'cp')

    nucleus = [m for m in listed(os.path.join(M, 'CPLOAD.EXEC'),
                                 r'&1 &2 &3 (\S+)')
               if m not in ('LOADER', 'LDT')]
    asmdmk = set(listed(os.path.join(M, 'ASMDMK.EXEC'), r'EXEC VMFASM (\S+)'))

    changed = {f.split('.')[0] for f in os.listdir(UPDATES)
               if f.endswith('.AUXLCL')}

    broken = {}
    for name in sorted(os.listdir(src)):
        if not name.endswith('.ASSEMBLE'):
            continue
        mod, text = name[:-9], open(os.path.join(src, name),
                                    errors='replace').read()
        hits = {s: len(re.findall(r'\b%s\b' % s, text)) for s in RENAMED}
        hits = {k: v for k, v in hits.items() if v}
        if hits:
            broken[mod] = hits

    print('CP MODULE STATUS  --  generated by tools/status.py')
    print()
    print('%-8s %-9s %-5s %s' % ('MEMBER', 'STATE', 'IN', 'NOTE'))
    print('-' * 78)

    rows = sorted(set(list(broken) + list(changed) + list(BASELINE_WARN)))
    for mod in rows:
        nucl = 'yes' if mod in nucleus else 'lib'
        if mod in changed and mod not in broken:
            state = 'CONVERTED'
            note = 'assembles clean, TXTLCL produced'
            if mod == 'DMKIOS':
                note = 'SSCH path done; TIO/HDV/TCH sites outstanding'
        elif mod in changed and mod in broken:
            state = 'PARTIAL'
            note = NEEDS.get(mod, '')
            if mod == 'DMKIOS':
                note = ('SSCH path done, clean on CE; TIO/HDV/TCH left. '
                        'Its lone source INTTIO site is absent from CE\'s '
                        'own build -- I-30')
        elif mod in broken:
            state = 'BROKEN'
            note = NEEDS.get(mod, ', '.join('%s x%d' % (k, v)
                                            for k, v in broken[mod].items()))
        else:
            state = 'warn'
            note = BASELINE_WARN[mod]
        print('%-8s %-9s %-5s %s' % (mod, state, nucl, note[:52]))

    if '--all' in sys.argv:
        print()
        print('Untouched and clean (%d in the nucleus):' % (
            len([m for m in nucleus if m not in rows])))
        rest = [m for m in nucleus if m not in rows]
        for i in range(0, len(rest), 9):
            print('  ' + ' '.join('%-8s' % m for m in rest[i:i + 9]))

    print()
    print('%-46s %s' % ('nucleus load-list modules', len(nucleus)))
    print('%-46s %s' % ('  covered by ASMDMK', len([m for m in nucleus
                                                    if m in asmdmk])))
    print('%-46s %s' % ('  no source anywhere (I-35)',
                        ' '.join(m for m in nucleus if m not in asmdmk)))
    print('%-46s %s' % ('converted, assembling clean',
                        len([m for m in changed if m not in broken])))
    print('%-46s %s' % ('broken by the PSA rename, awaiting work',
                        len([m for m in broken if m not in changed])))
    print('%-46s %s' % ('  of which guest-PSA swaps only (I-36)',
                        len([m for m in broken if m in GUEST_PSA])))
    print('%-46s %s' % ('untouched and clean',
                        len([m for m in nucleus if m not in rows])))


if __name__ == '__main__':
    main()
